# Application Name
spring.application.name=fase2

# Server Port
server.port=8080

# Actuator (Health Check)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
